---
version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /ZenPool/apps/LinuxAppsBackup/nginx/network_internal.conf:/etc/nginx/network_internal.conf
      - /ZenPool/apps/LinuxAppsBackup/nginx/proxy-wide.conf:/etc/nginx/conf.d/proxy-wide.conf
    network_mode: "host"
#    environment:
#      - NETWORK_ACCESS=internal
# This environment variable can be placed on any container to restrict access to internal network only

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=Australia/Melbourne
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  scrutiny:
    image: ghcr.io/linuxserver/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
        #- VIRTUAL_HOST=scrutiny.maximussmurf.com
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/scrutiny:/config
      - /run/udev:/run/udev:ro
    ports:
      - 8082:8080
    devices:
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
    restart: always

  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/tautulli:/config
      - /ZenPool/apps/LinuxAppsBackup/plex/Library/Application Support/Plex Media Server/Logs:/logs
    ports:
      - 8181:8181
    restart: always

  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: hydra2
    restart: always
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/nzbhydra2:/config
      - /ZenPool/downloads:/downloads
    env_file: uidgid.env
    environment:
      - VIRTUAL_HOST=nzbhydra2.maximussmurf.com
    expose:
      - 5076
    
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/nzbget:/config
      - /ZenPool/downloads/:/downloads
      - /ZenPool/movies/:/media/movies
      - /ZenPool/tv/:/media/tv
      - /ZenPool/anime/:/media/anime
      - /ZenPool/apps/:/media/apps
    expose :
      - 6789
    restart: always
    env_file: uidgid.env
    environment:
      - VIRTUAL_HOST=nzbget.maximussmurf.com

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/plex:/config
      - /ZenPool/tv:/data/tvshows
      - /ZenPool/movies:/data/movies
      - /ZenPool/anime:/data/anime
      - /ZenPool/transcode:/transcode
    network_mode: "host"
    restart: always
    env_file: uidgid.env
    environment:
      - VIRTUAL_HOST=plex.maximussmurf.com
      - VIRTUAL_PORT=32400

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/sonarr:/config
      - /etc/localtime:/etc/localtime:ro
      - /ZenPool/tv:/tv
      - /ZenPool/anime:/anime
      - /ZenPool/downloads:/downloads
    expose:
      - 8989
    restart: always
    env_file: uidgid.env
    environment:
      - VIRTUAL_HOST=sonarr.maximussmurf.com

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/radarr:/config
      - /ZenPool/movies:/movies
      - /ZenPool/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 7878
    restart: always
    env_file: uidgid.env
    environment:
      - VIRTUAL_HOST=radarr.maximussmurf.com
  
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    env_file: uidgid.env
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/ombi:/config
    expose:
      - 3579
    restart: always
    environment:
      - VIRTUAL_HOST=ombi.maximussmurf.com

  deluge:
    container_name: deluge
    image: ghcr.io/linuxserver/deluge
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ZenPool/apps/LinuxAppsBackup/deluge:/config
      - /ZenPool/downloads:/downloads
    ports:
      - 8112:8112
      - 58846:58846
    env_file: uidgid.env

  unifi:
    image: jacobalberty/unifi
    container_name: unifi
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /ZenPool/apps/LinuxAppsBackup/unifi2/lib:/var/lib/unifi
      - /ZenPool/apps/LinuxAppsBackup/unifi2/log:/var/log/unifi
      - /ZenPool/apps/LinuxAppsBackup/unifi2/run:/var/run/unifi
    ports:
      - 8443:8443
      - 8843:8843
      - 3478:3478/udp
      - 6789:6789
      - 8081:8080
      - 8880:8880
      - 10001:10001/udp
    env_file: uidgid.env
  
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    restart: always
    volumes:
      - /ZenPool/apps/LinuxAppsBackup/homeassistant2:/config
    environment:
      - TZ=Australia/Melbourne
    network_mode: "host"
